{% set name = "rp2paths" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python {{ python }}
  run:
    - python {{ python }}
    - openjdk
    - rdkit=2019.03.1.0
    - pandas
    - pydotplus
    - graphviz
    - python-graphviz
    - lxml

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: {{ data['description'] }}
  license: {{ data.get('license') }}
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - tduigou
