# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check

on:

  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**/RELEASE*'
      - '**/README*'
      - '**/LICENSE*'
      - 'recipe'
      - 'docs'
      - '.gitignore'
      - '.github'
      - '!.github/workflows/check*'
  pull_request:
    branches: [ master ]

jobs:

  Check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://continuumio/miniconda3

    - name: Updating conda
      run: conda update --all -y

    - name: Installing make
      run: conda install -y make

    - name: Checking package
      run: |
        cd ci
        make check-inconda
